version: 0.2

phases:
  install:
    commands:
    - docker version
    
  pre_build:
    commands:
    - echo "HI" 
    - pwd
    - cd node-docker
  build:
    commands:
    - pwd
    - docker build --tag node-docker .
    - docker tag node-docker:latest node-docker:v1.0
  post_build:
    commands:
    - pwd
    - docker images
    - ls
  
