version: 0.2

phases:
  install:
    commands:
    - docker version
    
  pre_build:
    commands:
    - echo "HI" 
    - aws --region us-east-1 ecr get-login-password | docker login --username AWS --password-stdin 770073169707.dkr.ecr.us-east-1.amazonaws.com
    - pwd
    - cd node-docker
  build:
    commands:
    - pwd
    - docker build --tag node-docker .
    - docker tag node-docker:latest node-docker:v1.0
  post_build:
    commands:
    - pwd
    - docker images
    - ls
    - docker run -d -p 8000:8000 node-docker:v1.0
    - docker ps
    - docker tag node-docker:latest 770073169707.dkr.ecr.us-east-1.amazonaws.com/node-docker:latest
    - curl -sv localhost:8000
    - docker push 770073169707.dkr.ecr.us-east-1.amazonaws.com/node-docker:latest
  
